### ISSUE TITLE
There is no Min/Max fields

### ISSUE THREAD

**Issue by pashata** [helgatheviking/woocommerce-mix-and-match-min-max#4]
After instaling this extension, there is no Min/Max fields in the mix and match tab ? I tried to trun of all the other plugins that might causing a trouble but still nothing, i have outdated woocommerce plugin , i updated it but still nothing , now i downgrade it becausi my theme is not updated yet for the new woocommerce. This is the site i'm using the plugin

http://mysoukdrawer.com.au/wpsouk/shop/mix/

**Comment by helgatheviking** [comment]
Hi @pashata,

First a reminder that this a free plugin and is not officially supported. So there's no timeline on when we might be able to help you, but I will do my best.

In the mean time, I would suggest cloning your site either locally or to a space like c9.io and testing against the more recent version of WooCommerce. Also, make sure the MNM plugin is up to date, because support was added for mini extensions fairly recently. And please test against a default theme to rule out conflicts from your theme.

If after following all your debugging steps you still can't resolve the issue then please send me admin creds via [my website](http://kathyisawesome.com/contact). 

Thanks,
-kathy

**Comment by helgatheviking** [comment]
@pashata I still cannot confirm this on my side.

**Comment by pashata** [comment]
And i can't do all the updates for the site because it needs to be launched and i don't want to make more complications if i made all the updates , the theme i used as a parent is not well coded and up to date. We are trying to set it to static values the min and max without the use of the exstension, if we can't figure it out i'll let you know and send you the admin info. Sry

**Comment by helgatheviking** [comment]
Reminder that you need at least MNM 1.0.7+ for this plugin to even work. I can't help you with a shoddy theme, though it shouldn't have much impact on the product meta box (but then you can never be sure what a truly crappy theme will attempt). Do yourself a favor and get a well-coded one. Having worked with crappy themes before too, it will definitely save you time in the long run.

**Comment by pashata** [comment]
Yeah , i know i should get a well coded one , but this one was an old site so i really don't have time to go back to that. I also think that the theme should not have impact on the product meta box , but i think that i got this warning 'WooCommerce Data Update Required – We just need to update your install to the latest version' might be the problem , but as i said i can't go back to that site now so i'm afraid if i update the woocommerce might screwup the site as it is ... anyway i hired a developer and we set the min and max to static in the original plugin so that's good for me now :D thank you for your time
